// Code generated by gobind. DO NOT EDIT.

// Java class mobile.GeneralConfig is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/Dreamacro/clash/mobile
package mobile;

import go.Seq;

/**
 * GeneralConfig 通用配置结构
 */
public final class GeneralConfig implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	GeneralConfig(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public GeneralConfig() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native long getPort();
	public final native void setPort(long v);
	
	public final native long getSocksPort();
	public final native void setSocksPort(long v);
	
	public final native long getMixedPort();
	public final native void setMixedPort(long v);
	
	public final native boolean getAllowLan();
	public final native void setAllowLan(boolean v);
	
	public final native String getMode();
	public final native void setMode(String v);
	
	public final native String getLogLevel();
	public final native void setLogLevel(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof GeneralConfig)) {
		    return false;
		}
		GeneralConfig that = (GeneralConfig)o;
		long thisPort = getPort();
		long thatPort = that.getPort();
		if (thisPort != thatPort) {
		    return false;
		}
		long thisSocksPort = getSocksPort();
		long thatSocksPort = that.getSocksPort();
		if (thisSocksPort != thatSocksPort) {
		    return false;
		}
		long thisMixedPort = getMixedPort();
		long thatMixedPort = that.getMixedPort();
		if (thisMixedPort != thatMixedPort) {
		    return false;
		}
		boolean thisAllowLan = getAllowLan();
		boolean thatAllowLan = that.getAllowLan();
		if (thisAllowLan != thatAllowLan) {
		    return false;
		}
		String thisMode = getMode();
		String thatMode = that.getMode();
		if (thisMode == null) {
			if (thatMode != null) {
			    return false;
			}
		} else if (!thisMode.equals(thatMode)) {
		    return false;
		}
		String thisLogLevel = getLogLevel();
		String thatLogLevel = that.getLogLevel();
		if (thisLogLevel == null) {
			if (thatLogLevel != null) {
			    return false;
			}
		} else if (!thisLogLevel.equals(thatLogLevel)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getPort(), getSocksPort(), getMixedPort(), getAllowLan(), getMode(), getLogLevel()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("GeneralConfig").append("{");
		b.append("Port:").append(getPort()).append(",");
		b.append("SocksPort:").append(getSocksPort()).append(",");
		b.append("MixedPort:").append(getMixedPort()).append(",");
		b.append("AllowLan:").append(getAllowLan()).append(",");
		b.append("Mode:").append(getMode()).append(",");
		b.append("LogLevel:").append(getLogLevel()).append(",");
		return b.append("}").toString();
	}
}

