// Code generated by gobind. DO NOT EDIT.

// Java class mobile.Mobile is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/Dreamacro/clash/mobile
package mobile;

import go.Seq;

public abstract class Mobile {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Mobile() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * CloseAllConnections 关闭所有连接
	 */
	public static native void closeAllConnections();
	/**
	 * CloseConnection 关闭指定连接
	 */
	public static native boolean closeConnection(String id);
	/**
	 * GetConfigDir 获取配置目录
	 */
	public static native String getConfigDir();
	/**
	 * GetConnections 获取当前连接信息
	 */
	public static native String getConnections();
	/**
	 * GetGeneral 获取通用配置
	 */
	public static native String getGeneral();
	/**
	 * GetMode 获取当前模式 (Rule/Global/Direct)
	 */
	public static native String getMode();
	/**
	 * GetProxies 获取所有代理信息 (JSON 格式)
	 */
	public static native String getProxies();
	/**
	 * GetProxyProviders 获取代理提供者信息 (JSON 格式)
	 */
	public static native String getProxyProviders();
	/**
	 * GetSelectedProxy 获取代理组当前选中的代理名称
	 */
	public static native String getSelectedProxy(String group);
	/**
	 * GetTrafficStats 获取流量统计
	 */
	public static native String getTrafficStats();
	/**
	 * GetVersion 获取 Clash 版本
	 */
	public static native String getVersion();
	/**
	 * HealthCheckProxyProvider 健康检查代理提供者
	 */
	public static native void healthCheckProxyProvider(String name) throws Exception;
	/**
	 * Init 初始化 Clash，设置主目录
	 */
	public static native void init(String home) throws Exception;
	/**
	 * IsRunning 返回 Clash 是否正在运行
	 */
	public static native boolean isRunning();
	/**
	 * ReloadConfig 重新加载配置
	 */
	public static native void reloadConfig() throws Exception;
	/**
	 * ResetTrafficStats 重置流量统计
	 */
	public static native void resetTrafficStats();
	/**
	 * SelectProxy 在代理组中选择指定代理
	 */
	public static native void selectProxy(String group, String proxyName) throws Exception;
	/**
	 * SetConfig 设置配置文件路径
	 */
	public static native void setConfig(String configPath);
	/**
	 * SetLogLevel 设置日志级别
	可选值: debug, info, warning, error, silent
	 */
	public static native void setLogLevel(String level);
	/**
	 * SetMode 设置模式
	可选值: Rule, Global, Direct
	 */
	public static native void setMode(String mode) throws Exception;
	/**
	 * StartTun 启动 TUN 设备
	fd: Android VpnService 创建的 TUN 文件描述符
	mtu: MTU 大小，通常为 9000
	 */
	public static native void startTun(long fd, long mtu) throws Exception;
	/**
	 * StartWithConfig 使用配置内容启动 Clash
	 */
	public static native void startWithConfig(String configContent) throws Exception;
	/**
	 * StartWithPath 使用配置文件路径启动 Clash
	 */
	public static native void startWithPath(String configPath) throws Exception;
	/**
	 * Stop 停止 Clash
	 */
	public static native void stop();
	/**
	 * StopTun 停止 TUN 设备
	 */
	public static native void stopTun();
	/**
	 * TestDelay 测试代理延迟 (毫秒)
	url: 测试用的 URL，如 &#34;https://www.gstatic.com/generate_204&#34;
	timeout: 超时时间（毫秒）
	 */
	public static native long testDelay(String proxyName, String url, long timeout) throws Exception;
	/**
	 * UpdateProxyProvider 更新代理提供者
	 */
	public static native void updateProxyProvider(String name) throws Exception;
	/**
	 * VerifyConfig 验证配置文件是否有效
	 */
	public static native void verifyConfig(String configPath) throws Exception;
	/**
	 * VerifyConfigContent 验证配置内容是否有效
	 */
	public static native void verifyConfigContent(String configContent) throws Exception;
}
