// Code generated by gobind. DO NOT EDIT.

// Java class mobile.ProviderInfo is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/Dreamacro/clash/mobile
package mobile;

import go.Seq;

/**
 * ProviderInfo 代理提供者信息
 */
public final class ProviderInfo implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ProviderInfo(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ProviderInfo() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getName();
	public final native void setName(String v);
	
	public final native String getType();
	public final native void setType(String v);
	
	// skipped field ProviderInfo.Proxies with unsupported type: []string
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ProviderInfo)) {
		    return false;
		}
		ProviderInfo that = (ProviderInfo)o;
		String thisName = getName();
		String thatName = that.getName();
		if (thisName == null) {
			if (thatName != null) {
			    return false;
			}
		} else if (!thisName.equals(thatName)) {
		    return false;
		}
		String thisType = getType();
		String thatType = that.getType();
		if (thisType == null) {
			if (thatType != null) {
			    return false;
			}
		} else if (!thisType.equals(thatType)) {
		    return false;
		}
		// skipped field ProviderInfo.Proxies with unsupported type: []string
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getName(), getType()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ProviderInfo").append("{");
		b.append("Name:").append(getName()).append(",");
		b.append("Type:").append(getType()).append(",");
		return b.append("}").toString();
	}
}

