// Code generated by gobind. DO NOT EDIT.

// Java class mobile.ProxyInfo is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/Dreamacro/clash/mobile
package mobile;

import go.Seq;

/**
 * ProxyInfo 代理信息
 */
public final class ProxyInfo implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ProxyInfo(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ProxyInfo() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getName();
	public final native void setName(String v);
	
	public final native String getType();
	public final native void setType(String v);
	
	public final native boolean getAlive();
	public final native void setAlive(boolean v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ProxyInfo)) {
		    return false;
		}
		ProxyInfo that = (ProxyInfo)o;
		String thisName = getName();
		String thatName = that.getName();
		if (thisName == null) {
			if (thatName != null) {
			    return false;
			}
		} else if (!thisName.equals(thatName)) {
		    return false;
		}
		String thisType = getType();
		String thatType = that.getType();
		if (thisType == null) {
			if (thatType != null) {
			    return false;
			}
		} else if (!thisType.equals(thatType)) {
		    return false;
		}
		boolean thisAlive = getAlive();
		boolean thatAlive = that.getAlive();
		if (thisAlive != thatAlive) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getName(), getType(), getAlive()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ProxyInfo").append("{");
		b.append("Name:").append(getName()).append(",");
		b.append("Type:").append(getType()).append(",");
		b.append("Alive:").append(getAlive()).append(",");
		return b.append("}").toString();
	}
}

