// Code generated by gobind. DO NOT EDIT.

// Java class mobile.TrafficStats is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/Dreamacro/clash/mobile
package mobile;

import go.Seq;

/**
 * TrafficStats 流量统计结构
 */
public final class TrafficStats implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	TrafficStats(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public TrafficStats() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native long getUp();
	public final native void setUp(long v);
	
	public final native long getDown();
	public final native void setDown(long v);
	
	public final native long getUpTotal();
	public final native void setUpTotal(long v);
	
	public final native long getDownTotal();
	public final native void setDownTotal(long v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof TrafficStats)) {
		    return false;
		}
		TrafficStats that = (TrafficStats)o;
		long thisUp = getUp();
		long thatUp = that.getUp();
		if (thisUp != thatUp) {
		    return false;
		}
		long thisDown = getDown();
		long thatDown = that.getDown();
		if (thisDown != thatDown) {
		    return false;
		}
		long thisUpTotal = getUpTotal();
		long thatUpTotal = that.getUpTotal();
		if (thisUpTotal != thatUpTotal) {
		    return false;
		}
		long thisDownTotal = getDownTotal();
		long thatDownTotal = that.getDownTotal();
		if (thisDownTotal != thatDownTotal) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getUp(), getDown(), getUpTotal(), getDownTotal()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("TrafficStats").append("{");
		b.append("Up:").append(getUp()).append(",");
		b.append("Down:").append(getDown()).append(",");
		b.append("UpTotal:").append(getUpTotal()).append(",");
		b.append("DownTotal:").append(getDownTotal()).append(",");
		return b.append("}").toString();
	}
}

